<?php
  $categories=array("Vegetables", "Fruits", "Dairy",  "Flavorings", "Liquids", "Grains", "Grain Products","Baked Goods", "Legumes & Nuts", "Meats",  "Fish", "Vegetarian", "Baking Supplies", "Fats & Oils", "Accompaniments", "Miscellaneous" );
    $vegetables=array("Roots", "Tubers", "Stalk Vegetables", "Onions", "Garlic", "Ginger & Other Rhizomes", "Cabbages", "Salad Greens","Cooking Greens", "Inflorescent Vegetables","Snap Beans", "Edible Pods", "Fresh Peas", "Fresh Beans", "Mushrooms", "Fruit Vegetables", "Sea Vegetables", "Sprouts", "Other Vegetables")
      $roots=array("beet", "black radish", "burdock", "carrot", "celeriac", "coriander root", "horseradish", "lotus root", "parsely root", "parsnip", "radish", "rutabaga", "salsify", "turnip");
      $tubers=array("arracacha", "arrowroot", "cassava", "chinese artichoke", "jerusalem artichoke", "jicama", "malanga", "Bintje potato", "boiling potato", "caribe potato", "fingerling potato", "huckleberry potato", "long white potato", "new potatoes", "oca potato", "purple potato", "red-skinned potato", "russet potato", "white round potato", "yellow finn potato", "yukon gold potato", "boniato", "Japanese yam", "Okinawan purple potato", "sweet potato", "tropical yam", "yam", "yamaimo", "taro", "water chestnut");
      $stalkVegetables=array("asparagus", "bamboo shoots", "cardoon", "celery", "chinese celery", "fennel", "fiddlehead fern", "hearts of palm", "rhubarb", "white asparagus", "wild asparagus");
      $onions=array("green onion", "ramps", "leek", "spring onion", "pearl onion", "sweet onion", "yellow onion", "white onion", "shallot", "cippolini onion", "boiling onion", "bermuda onion");
      $garlic=array("garlic", "garlic greens", "garlic powder");
      $ginger=array("fingerroot", "galangal", "green ginger", "ginger root", "lesser galangal", "miyoga", "turmeric");
      $cabbages=array("bok choy", "brussels sprouts", "flowering kale", "green cabbage", "kohlrabi", "napa cabbage", "red cabbage", "savoy cabbage", "su choy", "yau choy");
      $saladGreens=array("arugula", "Belgian endive", "Bibb lettuce", "Boston lettuce", "corn salad", "cress", "curly endive", "dandelions", "red endive", "escarole", "green leaf lettuce", "iceberg lettuce", "lettuce", "lollo rosso", "mizuna", "oakleaf lettuce", "radicchio", "red-leaf lettuce", "red orach", "red mustard", "romaine lettuce", "spring salad mix", "tat soi", "trefoil", "winter purslane");
      $cookingGreens=array("broccoli raab", "beet greens", "callaloo", "celtuce", "Chinese broccoli", "Chinese spinach", "chrysanthemum leaves", "collard greens", "gai choy", "jam leaf", "jute leaf", "kale", "kohlrabi greens", "Malabar spinach", "mustard greens", "nettles", "pumpkin leaves", "purslane", "quail grass", "radish greens", "sorrel", "spinach", "swiss chard", "turnip greens", "water spinach");
      $inflorescentVegetables=array("artichoke", "banana flower", "broccoflower", "broccoli", "broccoli Romanesco", "broccolini", "cauliflower", );
      $snapBeans=array("chepil", "dragon tongue bean", "green bean", "haricot verts", "Italian flat bean", "sator", "Thailand long bean", "wax bean", "winged bean", "yard-long bean");
      $ediblePods=array("okra", "snow pea", "sugar snap");
      $freshPeas=array("fresh black-eyed pea", "garden pea");
      $freshBeans=array("fresh cannellini bean", "fresh cranberry bean", "edamame", "fresh fava bean", "fresh lima bean");
      $mushrooms=array("abalone cap mushroom", "bear's head mushroom", "black trumpet mushroom", "blewitt mushrooms", "cauliflower mushroom", "chanterelle", "chestnut mushroom", "chicken-of-the-woods mushroom","cinnamon cap mushroom","clamshell mushroom", "cloud ear mushroom", "cremini mushroom", "enoki mushroom", "eryngii mushroom", "fairy-ring mushroom", "gamboni mushroom", "hawk's wing mushroom", "hedgehog mushroom", "huitlacoche", "lobster mushroom", "maitake mushroom", "matsutake mushroom", "morels", "nameko mushroom", "oyster mushroom","pom pom mushroom", "puff ball mushroom", "porcino", "portobello mushroom", "red oyster mushroom", "shiitake mushroom", "shimeji mushroom", "silver ear mushroom", "St. George's mushroom", "straw mushroom", "truffles", "trumpet royale mushroom", "white chanterelle mushroom", "white mushroom", "winecap mushroom", "wood ear mushroom", "yellow foot mushroom");
      $fruitVegetables=array("cherry tomato", "currant tomato", "grape tomato", "green tomato", "sauce tomato", "slicing tomato", "teardrop tomato", "vine tomato", "American eggplant", "apple green eggplant", "Chinese eggplant", "dried eggplant", "Filipino eggplant", "green goddess eggplant", "Hawaiian eggplant", "Holland eggplant", "Indian eggplant", "Italian eggplant", "Japanese eggplant", "pea eggplants", "Rosa Bianca eggplant", "Sicilian eggplant", "Thai eggplant", "white eggplant", "acorn squash", "banana squash", "butternut squash", "buttercup squash", "calabaza", "delicata squash", "golden delicious squash", "golden nugget squash", "Hubbard squash", "kabocha squash", "pumpkin", "spaghetti squash", "sweet dumpling squash", "turban squash", "cucuzza", "chayote", "globe squash", "pattypan squash", "scallopini", "tinda", "yellow squash", "zucchini", "bitter melon", "chinese okra", "fuzzy melon", "Indian bitter melon", "opo squash", "winter melon", "Armenian cucumber", "English cucumber", "Japanese cucumber", "cornichon", "gherkin", "Kirby cucumber", "lemon cucumber", "garden cucumber", "Mediterranean cucumber", "Persian cucumber", "bell pepper", "bull's horn", "cachucha pepper", "cubanelle", "Holland bell pepper", "lamuyo", "pimento", "sweet banana pepper", "Anaheim chile", "banana pepper", "cayenne pepper", "cherry pepper", "cuaresmeno", "chilaca", "Fresno pepper", "guero", "habanero chile", "Holland chile", "hontaka pepper", "jalapeno pepper", "malagueta pepper", "mazana chile", "mirasol pepper", " New Mexico green chile", "piquant pepper", "rocotillo", "poblano pepper (fresh)", "rocoto chile", "Scotch bonnet chile", "serrano pepper", "shishito chile", "Thai chile", "xcatic chile", "yellow wax pepper", "ají panca chile", "ancho chile pepper", "California chile", "cascabel pepper", "Catarina chile", "cayenne pepper", "Chilhuacle negro chile", "Chilcostle chile", "chile de arbol", "chipotle pepper (chile)", "Costeño Amarillo chile", "guajillo chile", "habanero (habañero) chile (or pepper)", "Japanese dried chile", "mirasol chile (dried)", "mora chile", "morita pepper", "mulato chile", "New Mexico red chile", "Onza roja chile", "pasilla chile", "pequin pepper", "piri piri pepper", "puya chile", "tepin (tepín)", "tepin (tepín)", "black olives", "green olives", "avocado", "tomatillo");
      $seaVegetables=array("arame", "dulse", "hair vegetable", "hijiki", "konbu", "sushi nori", "laver", "salted seaweed", "seabean", "wakamw" );
      $sprouts=array("alfalfa sprouts", "broccoli sprouts", "buckwheat sprouts", "daikon sprouts", "fenugreek sprouts", "mung bean sprouts", "onion sprouts", "snow pea shoots", "soybean sprouts", "sunflower sprouts");
      $otherVegetables=array("nopale", "nopalitos");
 ?>
